eureka:
    instance:
      prefer-ip-address: true #使用ip注册，否则会使用主机名注册了(此处考虑到对老版本的兼容，新版本经过实验都是ip)
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
spring:
  zipkin:
    base-url: http://106.14.163.235:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 111.231.119.253
    port: 5672
    username: root
    password: root
  datasource:
     name: dev
     url: jdbc:mysql://172.16.31.3:3306/mitongmallcloud
     username: root
     password: 2rjaFvus
redis:
    host: 111.231.119.253
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
