eureka:
  instance:
    prefer-ip-address: true #使用ip注册，否则会使用主机名注册了(此处考虑到对老版本的兼容，新版本经过实验都是ip)
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
spring:
  redis:
    host: 172.16.31.3
    port: 6379
    password: yangfanfinland
  zipkin:
    base-url: http://106.14.163.235:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
     name: dev
     url: jdbc:mysql://172.16.31.3:3306/mitongmallcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
     username: root
     password: root
redis:
    host: 172.16.31.3
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
zk:
  host: 111.231.119.253
